server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: postgres
    password: Abdulloh96abdulloh
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

